# -*- coding: utf-8 -*-
"""OCR-Analyzer_gemini_v0.1.0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cxspZcvKOj1O36RXmRB1t-0unBQ_Inze

# OCR Analyzer
**Autor:** engcontrol-alv
"""

import os
import shutil
import uvicorn
import traceback
from pyngrok import ngrok
from fastapi import FastAPI, UploadFile, File, Form
from fastapi.middleware.cors import CORSMiddleware
import google.generativeai as genai
from pypdf import PdfReader
from pdf2image import convert_from_path
import pytesseract

# Load Ngrok token from environment for secure tunneling
ngrok_token = os.getenv("NGROK_AUTHTOKEN")
if ngrok_token:
    ngrok.set_auth_token(ngrok_token)

# --- Core Processing Functions ---

def extract_text_from_scanned_pdf(pdf_path):
    """
    Fallback method for image-based PDFs.
    Requires Poppler and Tesseract installed on the host system.
    """
    try:
        # Convert PDF pages to images (300 DPI for better OCR accuracy)
        images = convert_from_path(pdf_path, dpi=300)
        extracted_content = []

        for i, image in enumerate(images):
            # Run OCR supporting both Portuguese and English
            page_text = pytesseract.image_to_string(image, lang='por+eng')
            extracted_content.append(f"--- Page {i+1} ---\n{page_text}")

        return "\n".join(extracted_content)
    except Exception as e:
        print(f"[OCR ERROR] {str(e)}")
        return None

def process_document(file_path):
    """
    Determines if the PDF is text-based or scanned and applies the appropriate extraction method.
    """
    try:
        text_content = ""
        is_scanned = False

        if file_path.lower().endswith('.pdf'):
            reader = PdfReader(file_path)
            for page in reader.pages:
                content = page.extract_text()
                if content:
                    text_content += content + "\n"

            # Heuristic: If extracted text length is negligible (< 50 chars),
            # treat as image-based PDF and trigger OCR.
            if len(text_content.strip()) < 50:
                is_scanned = True
        else:
            # Fallback for plain text files
            with open(file_path, 'r', encoding='utf-8') as f:
                text_content = f.read()

        if is_scanned:
            ocr_result = extract_text_from_scanned_pdf(file_path)
            if not ocr_result:
                raise RuntimeError("OCR extraction failed.")
            return ocr_result

        return text_content
    except Exception as e:
        print(f"[FILE PROCESS ERROR] {str(e)}")
        return None

def generate_technical_analysis(context, query, api_key):
    try:
        # Configure API key per request (Stateless/Zero Trust approach)
        genai.configure(api_key=api_key)

        model_name = 'gemini-1.5-flash'
        model = genai.GenerativeModel(model_name)

        system_instruction = f"""
        Role: Senior Industrial Engineer & Technical Analyst.
        Task: Analyze the provided technical documentation and answer the user query.

        Context:
        {context[:500000]}

        User Query: {query}

        Guidelines:
        1. Language: Portuguese (PT-BR).
        2. Tone: Professional, technical, and objective.
        3. Accuracy: Base your answer strictly on the provided context.
        """

        response = model.generate_content(system_instruction)
        return response.text

    except Exception as e:
        print(f"[LLM ERROR] {str(e)}")
        traceback.print_exc()
        return "Service unavailable. Please verify API credentials or try again later. (Error: 503)"

# --- API Initialization ---

app = FastAPI(title="Industrial Doc Analyst API", version="1.0.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Volatile storage for session context (RAM only, no persistence)
context_store = {}

@app.post("/analyze")
async def analyze_endpoint(
    question: str = Form(...),
    file: UploadFile = File(None),
    google_key: str = Form(...)
):
    # Basic Security Validation
    if not google_key or len(google_key) < 20:
        return {"answer": "Authentication failed. Invalid API Key."}

    # Derive session ID from key signature to maintain context continuity
    session_id = google_key[-10:]

    # File Handling Logic
    if file:
        temp_filename = f"tmp_{file.filename}"
        try:
            with open(temp_filename, "wb") as buffer:
                shutil.copyfileobj(file.file, buffer)

            print(f"[INFO] Processing file: {file.filename}")
            extracted_text = process_document(temp_filename)

            if extracted_text:
                context_store[session_id] = extracted_text
            else:
                return {"answer": "Document could not be processed or is empty."}

        except Exception as e:
            print(f"[UPLOAD ERROR] {str(e)}")
            return {"answer": "Internal server error during file processing."}
        finally:
            # Ensure ephemeral file existence: write to disk, process, and delete immediately.
            if os.path.exists(temp_filename):
                os.remove(temp_filename)

    # Check if context exists in memory
    if session_id not in context_store:
        return {"answer": "No active document context found. Please upload a file."}

    # Execute Inference
    result = generate_technical_analysis(context_store[session_id], question, google_key)
    return {"answer": result}

# --- Server Entry Point ---

if __name__ == "__main__":
    try:
        # Attempt to establish secure tunnel automatically
        public_url = ngrok.connect(8000).public_url
        print(f"[*] Tunnel Established: {public_url}")
    except Exception as e:
        print(f"[WARN] Ngrok tunnel could not be started: {e}")

    uvicorn.run(app, host="0.0.0.0", port=8000, log_level="info")